// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klpkxpzvwwdpnalegpre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscGt4cHp2d3dkcG5hbGVncHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODAwNjIsImV4cCI6MjA3MTQ1NjA2Mn0.YRLwZN4hdbthM-0RpDKc2eUvTkGLK16BERlHt3Z0jx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});