// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer environment variables set via Vite; fall back to existing values
const PROJECT_ID = (import.meta as any)?.env?.VITE_SUPABASE_PROJECT_ID;
const SUPABASE_URL = (import.meta as any)?.env?.VITE_SUPABASE_URL || (PROJECT_ID ? `https://${PROJECT_ID}.supabase.co` : "https://klpkxpzvwwdpnalegpre.supabase.co");
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any)?.env?.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscGt4cHp2d3dkcG5hbGVncHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODAwNjIsImV4cCI6MjA3MTQ1NjA2Mn0.YRLwZN4hdbthM-0RpDKc2eUvTkGLK16BERlHt3Z0jx0";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // eslint-disable-next-line no-console
  console.error("Supabase configuration is missing. Check VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});